
# Site settings
title:            Vanntechs Web Studio
email:            vanessa@vanntechs.com
description:      Vanntechs Web Studio is a web agency based in Montreal and surrounding areas.
baseurl:          ''
url:              'http://vanntechs.com'
github_username:  vthaihien1412

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  vincent:
    name:             Vincent Vu
    bio:              Graphic Designer of Vanntechs.
